server :
  port : 3001
  servlet :
    context-path : /start2
# 自定义配置
email: 
  user: 
    - 2675130594@qq.com
    - ginlon5241@gmail.com
  code: 123123
  host: 'smtp.qq.com'
  auth: true
spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: ginlon